    traySnapshot,
    taskDetailId,
    taskDetail,
    taskDetailLoading,
    selectedRecordId,
    recordDetail,
    focusedProjectId,
    projectSettings,
    loading,
    lastError,
    // getters
    todayFocusMinutes,
    completedTasks,
    pendingTasks,
