/Users/xiaoye/Desktop/electron-tools/src/shared/__tests__/calc.test.ts
/Users/xiaoye/Desktop/electron-tools/src/shared/__tests__/fallbackCommands.test.ts
/Users/xiaoye/Desktop/electron-tools/src/shared/__tests__/unitConverter.test.ts
/Users/xiaoye/Desktop/electron-tools/src/shared/__tests__/emoji.test.ts
/Users/xiaoye/Desktop/electron-tools/src/shared/__tests__/searchBoost.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/__tests__/ipcContract.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/launcher/__tests__/netGuard.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/launcher/__tests__/market.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/modules/__tests__/expansionBuffer.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/modules/__tests__/dialogs.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/modules/__tests__/expansionTemplate.test.ts
/Users/xiaoye/Desktop/electron-tools/src/renderer/src/composables/__tests__/useRegionCapture.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/__tests__/RecoveryManager.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/__tests__/RecordingHistoryServiceLegacy.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/RecordingExportService.advanced.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/SegmentService.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/GifEncoderService.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/RegionOverlayMultiMonitor.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/CountdownService.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/GlobalShortcutService.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/systemAudioPatterns.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/services/recording/__tests__/RecordingExportService.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/stores/__tests__/RecordingSettingsSystemAudio.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/utils/__tests__/index.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/utils/__tests__/platform.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/db/__tests__/legacyArchiveList.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/db/__tests__/PrefRepository.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/db/__tests__/RecordingRepository.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/db/__tests__/dataMigrations.test.ts
/Users/xiaoye/Desktop/electron-tools/src/main/db/__tests__/MarkerRepository.test.ts
---
