/**
 * Frond · Lorem Ipsum 占位文本插件核心逻辑（lib.js）
 * UMD 双导出：插件页挂 globalThis.FrondLoremLib，vitest（node）走 module.exports。
 */
;(function (root, factory) {
  var api = factory()
  if (typeof module === 'object' && module.exports) module.exports = api
  if (root && typeof root === 'object') root.FrondLoremLib = api
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  var LATIN_WORDS = ['lorem',
    'ipsum',
    'dolor',
    'sit',
    'amet',
    'consectetur',
    'adipiscing',
    'elit',
    'sed',
    'do',
    'eiusmod',
    'tempor',
    'incididunt',
    'ut',
    'labore',
    'et',
    'dolore',
    'magna',
    'aliqua',
    'enim',
    'ad',
    'minim',
    'veniam',
    'quis',
    'nostrud',
    'exercitation',
    'ullamco',
    'laboris',
    'nisi',
    'aliquip',
    'ex',
    'ea',
    'commodo',
    'consequat',
    'duis',
    'aute',
    'irure',
    'in',
    'reprehenderit',
    'voluptate',
    'velit',
    'esse',
    'cillum',
    'fugiat',
    'nulla',
    'pariatur',
    'excepteur',
    'sint',
    'occaecat',
    'cupidatat',
    'non',
    'proident',
    'sunt',
    'culpa',
    'qui',
    'officia',
    'deserunt',
    'mollit',
    'anim',
    'id',
    'est',
    'laborum',
    'sed',
    'ut',
    'perspiciatis',
    'unde',
    'omnis',
    'iste',
    'natus',
    'error',
    'voluptatem',
    'accusantium',
    'doloremque',
    'laudantium',
    'totam',
    'rem',
    'aperiam',
    'eaque',
    'ipsa',
    'quae',
    'ab',
    'illo',
    'inventore',
    'veritatis',
    'quasi',
    'architecto',
    'beatae',
    'vitae',
    'dicta',
    'sunt',
    'explicabo',
    'nemo',
    'ipsam',
    'quia',
    'voluptas',
    'aspernatur',
    'aut',
    'odit',
    'fugit',
    'consequuntur',
    'magni',
    'dolores',
    'eos',
    'qui',
    'ratione',
    'sequi',
    'nesciunt',
    'neque',
    'porro',
    'quisquam',
    'est',
    'dolorem',
    'ipsum',
    'dolor',
    'amet',
    'consectetur',
    'adipisci',
    'velit',
    'non',
    'numquam',
    'eius',
    'modi',
    'tempora',
    'incidunt',
    'ut',
    'labore',
    'dolore',
    'magnam',
    'aliquam',
    'quaerat',
    'voluptatem',
    'ut',
    'enim',
    'ad',
    'minima',
    'veniam',
    'quis',
    'nostrum',
    'exercitationem',
    'ullam',
    'corporis',
    'suscipit',
    'laboriosam',
    'nisi',
    'ut',
    'aliquid',
    'ex',
    'ea',
    'commodi',
    'consequatur',
    'aut',
    'perferendis',
    'doloribus',
    'asperiores',
    'repellat',
    'at',
    'vero',
    'eos',
    'accusamus',
    'iusto',
    'odio',
    'dignissimos',
    'ducimus',
    'blanditiis',
    'praesentium',
    'voluptatum',
    'deleniti',
    'atque',
    'corrupti',
    'quos',
    'quas',
    'molestias',
    'excepturi',
    'sint',
    'occaecati',
    'cupiditate',
    'non',
    'provident',
    'similique',
    'sunt',
    'in',
    'culpa',
    'qui',
    'officia',
    'deserunt',
    'mollitia',
    'animi',
    'id',
    'est',
    'laborum',
    'dolorum',
    'fuga',
    'et',
    'harum',
    'quidem',
    'rerum',
    'facilis',
    'est',
    'et',
    'expedita',
    'distinctio',
    'nam',
    'libero',
    'tempore',
    'cum',
    'soluta',
    'nobis',
    'est',
    'eligendi',
    'optio',
    'cumque',
    'nihil',
    'impedit',
    'quo',
    'porro',
    'quisquam',
    'est',
    'qui',
    'minus',
    'id',
    'quod',
    'maxime',
    'placeat',
    'facere',
    'possimus',
    'omnis',
    'voluptas',
    'assumenda',
    'est',
    'omnis',
    'dolor',
    'repellendus',
    'temporibus',
    'autem',
    'quibusdam',
    'officiis',
    'debitis',
    'aut',
    'rerum',
    'necessitatibus',
    'saepe',
    'eveniet',
    'voluptates',
    'repudiandae',
    'sint',
    'et',
    'molestiae',
    'non',
    'recusandae',
    'itaque',
    'earum',
    'rerum',
    'hic',
    'tenetur',
    'a',
    'sapiente',
    'delectus',
    'ut',
    'aut',
    'reiciendis',
    'voluptatibus',
    'maiores',
    'alias',
    'consequatur',
    'aut',
    'perferendis',
    'doloribus',
    'asperiores',
    'repellat']

  var ZH_WORDS = [
    '产品', '设计', '体验', '交互', '视觉', '效率', '工具', '桌面', '启动', '搜索',
    '片段', '任务', '清单', '灵感', '笔记', '创作', '专注', '节奏', '协作', '分享',
    '灵感一闪', '随手记录', '高效工作', '极简主义', '沉浸体验', '优雅呈现'
  ]

  function pick(arr) {
    return arr[Math.floor(Math.random() * arr.length)]
  }

  function words(n, list) {
    var out = []
    for (var i = 0; i < n; i++) out.push(pick(list))
    return out.join(' ')
  }

  function sentence(list) {
    var n = 8 + Math.floor(Math.random() * 12)
    var w = words(n, list)
    return w.charAt(0).toUpperCase() + w.slice(1) + pick(['.', '.', '.', '!', '?'])
  }

  function sentences(n, list) {
    var out = []
    for (var i = 0; i < n; i++) out.push(sentence(list))
    return out.join(' ')
  }

  function paragraphs(n, list) {
    var out = []
    for (var i = 0; i < n; i++) out.push(sentences(3 + Math.floor(Math.random() * 3), list))
    return out.join('\n\n')
  }

  /**
   * kind: 'words' | 'sentences' | 'paragraphs'；lang: 'latin' | 'zh'。
   * n 封顶 200（words）/ 50（sentences）/ 20（paragraphs）。
   */
  function generate(kind, n, lang) {
    var list = lang === 'zh' ? ZH_WORDS : LATIN_WORDS
    var count = Math.max(1, Math.floor(Number(n) || 1))
    if (kind === 'words') return words(Math.min(count, 200), list)
    if (kind === 'sentences') return sentences(Math.min(count, 50), list)
    if (kind === 'paragraphs') return paragraphs(Math.min(count, 20), list)
    return words(count, list)
  }

  return { generate: generate }
})
